### ISSUE TITLE
Error processing tar file

### ISSUE THREAD

**Issue by sirgogo** [IntelPython/container-images#1]
Hi,
I receive the following error when pulling from your docker image:
```
$ docker pull intelpython/intelpython3_full
Using default tag: latest
latest: Pulling from intelpython/intelpython3_full
8ad8b3f87b37: Pull complete 
e04db1209ac4: Pull complete 
edc7ae7e687c: Pull complete 
4a7b3487193b: Pull complete 
4f4f8387a4e8: Extracting [==================================================>]  1.785GB/1.785GB
failed to register layer: Error processing tar file(exit status 1): link /opt/conda/pkgs/opencv-3.1.0-np112py35_intel_5/share/OpenCV/haarcascades/haarcascade_eye_tree_eyeglasses.xml /opt/conda/share/OpenCV/haarcascades/haarcascade_eye_tree_eyeglasses.xml: no such file or directory
```
This occurs on OSX host and Linux (ubuntu 16.04) hosts.
Interestingly, I get the same error when I build from scratch (installing intel-python package with silent mode, adding to default path, etc) in my own/custom docker image, even though it builds successfully on Docker Hub.
Any ideas?

**Comment by rscohn2** [comment]
One other user has seen it, but I am unable to reproduce the problem. Which version of docker are you using?

rscohn1@fxsatlin04$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rscohn1@fxsatlin04$ docker pull intelpython/intelpython3_full
Using default tag: latest
latest: Pulling from intelpython/intelpython3_full
8ad8b3f87b37: Pull complete 
e04db1209ac4: Pull complete 
edc7ae7e687c: Pull complete 
4a7b3487193b: Pull complete 
4f4f8387a4e8: Pull complete 
Digest: sha256:f379356dbfaf592d8b950becec3e730264808b1ea442041f7657e31dd89437c9
Status: Downloaded newer image for intelpython/intelpython3_full:latest
rscohn1@fxsatlin04$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
intelpython/intelpython3_full   latest              fd109d50402a        4 weeks ago         4.63 GB
rscohn1@fxsatlin04$ df -h /var/lib/docker
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda7       731G   12G  682G   2% /
rscohn1@fxsatlin04$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
rscohn1@fxsatlin04$

**Comment by triskadecaepyon** [comment]
@sirgogo , I've gotten a different problem during pulling the image, but was able to download it successfully on the second try–it might be from the dockerhub side that is causing problems.  Could you try it again and report back?

Initial try:

`$ docker pull intelpython/intelpython3_full
Using default tag: latest
latest: Pulling from intelpython/intelpython3_full
8ad8b3f87b37: Pull complete 
e04db1209ac4: Pull complete 
edc7ae7e687c: Pull complete 
4a7b3487193b: Pull complete 
4f4f8387a4e8: Extracting [=======>                                                         ]  218.9MB/1.785GB
unexpected EOF`

And after pulling a second time:

`$ docker pull intelpython/intelpython3_full
Using default tag: latest
latest: Pulling from intelpython/intelpython3_full
8ad8b3f87b37: Pull complete
e04db1209ac4: Pull complete
edc7ae7e687c: Pull complete
4a7b3487193b: Pull complete
4f4f8387a4e8: Pull complete
Digest: sha256:f379356dbfaf592d8b950becec3e730264808b1ea442041f7657e31dd89437c9
Status: Downloaded newer image for intelpython/intelpython3_full:latest
`

I'm using docker 17.05.0-ce on Ubuntu 16.04 LTS.  Let me know if the problem has gone away or still persists.

**Comment by triskadecaepyon** [comment]
@sirgogo, just checking in: is it solved for you?

**Comment by sirgogo** [comment]
@triskadecaepyon , sorry for the delay, I was waiting to check on my remote Ubuntu machine.
Updates:
It did not work on OSX until I updated to *edge* branch of docker (17.06.*), then it pulls after second attempt.
It pulls fine on Fedora F24/F25 (docker version 1.10.3 and 1.12.6, respectively).
It also pulls fine on Debian (docker version 17.05.0-ce on Debian stretch).
However, it does _not_ pull properly on my synology, even with multiple attempts (docker version 1.12.* I believe..).
My remote ubuntu machine went down, so I can't test yet, but maybe it will work? It seems to me a combination of docker version & docker.io, but I can't figure out why it didn't work on synology... maybe there is an intermediate build that has this problem?

**Comment by triskadecaepyon** [comment]
@sirgogo , do you get the same error as before on synology machines? Please let me know if the Ubuntu version (once it comes back up) exhibits the issue.

On another note, I think the version of Docker and Dockerhub behavior may be the a trigger for it - my other machines on older docker versions run into the issue but after updating them, it fixes the problem.

**Comment by sirgogo** [comment]
On a Synology machine:
```
sirgogo@longboard-syno:~$ sudo docker -v
Password: 
Docker version 1.11.2, build 5be46ee-synology
sirgogo@longboard-syno:~$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sirgogo@longboard-syno:~$ sudo docker pull intelpython/intelpython3_full
Using default tag: latest
latest: Pulling from intelpython/intelpython3_full

8ad8b3f87b37: Pull complete 
e04db1209ac4: Pull complete 
edc7ae7e687c: Pull complete 
4a7b3487193b: Pull complete 
4f4f8387a4e8: Extracting 1.785 GB/1.785 GB
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: link /opt/conda/pkgs/opencv-3.1.0-np112py35_intel_5/share/OpenCV/haarcascades/haarcascade_eye_tree_eyeglasses.xml /opt/conda/share/OpenCV/haarcascades/haarcascade_eye_tree_eyeglasses.xml: no such file or directory
```
Same error as before. Waiting to check on ubuntu machine. Yes, maybe a update to synology build would fix it. Haven't figured it out yet.

**Comment by triskadecaepyon** [comment]
@sirgogo , yes that is quite odd.  I'd always try to update the Docker version on the Synology machine, as I know they've had a few fixes for layers and file systems before they moved to the Docker CE version system.  How did the Ubuntu machine turn out?

**Comment by triskadecaepyon** [comment]
@sirgogo , checking in one last time.  Did it work on the Ubuntu machine for you?

**Comment by sirgogo** [comment]
Thanks for checking back. Yes, it worked on the Ubuntu machine. I think the issue was due to the switch over from old docker versions to the CE build. Synology still doesn't work, but hopefully it will fix in the next update. Doesn't seem to be a problem with the way the image is built, just how its distributed.
Can close now, I think. Thanks for your help.
