### ISSUE TITLE
Intel Xeon Phi X200 7210 - 64-core MKL Question

### ISSUE THREAD

**Issue by FuriouslyCurious** [IntelPython/container-images#3]
Hi Intel Dev Team,
I am using Intel Python on Intel Xeon Phi 7210 CPU with 64 core CPUs. 

What environment variables do you recommend setting to optimize Intel Python execution for this processor?  My current environment vars are:

```
export OMP_NUM_THREADS=16 MKL_NUM_THREADS=8
export MKL_DYNAMIC=TRUE OMP_DYNAMIC=TRUE OMP_NESTED=TRUE
export MKL_MIC_ENABLE=1
export MIC_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
```

Using above variables seems to be using normal MKL library, not the MKL-MIC libraries. 

Thanks!

**Comment by rscohn2** [comment]
The MKL_MIC_ENABLE and MIC_LD_LIBRARY_PATH setting you have are appropriate
for KNC, but are not needed for your KNL system.

If you are not using threads in python, and are OK with MKL using all the
cores, then you do not need any settings.

Are you trying to use the docker container on KNL? The container does not
contain some libraries that MKL needs to use the MCDRAM and performance may
not be good.

**Comment by FuriouslyCurious** [comment]
Hi Robert, 

Yes - I am trying to use Docker container on KNL, and I am happy to let MKL saturate all cores.  Based on your first suggestion, I will go ahead and remove MKL_MIC_ENABLE and MIC_LD_LIBRARY_PATH env vars from my Dockerfile.

Regarding your second suggestion, how can I obtain the libraries required for IntelPython KNL MCDRAM performance?  I will appreciate it if you point me in the right direction, because almost all information I can find online is for KNC, and not applicable for KNL.

Thank you!

**Comment by rscohn2** [comment]
Here is a [white paper](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/running-docker-containers-xeon-phi-whitepaper.pdf) about using docker on KNL. There is a sample dockerfile that shows how to install memkind and other useful software for KNL.
