### ISSUE TITLE
MPI seems broken in the IntelPython docker images

### ISSUE THREAD

**Issue by TylerBackman** [IntelPython/container-images#6]
The following produces a segmentation fault:
```
docker run -it --rm intelpython/intelpython3_full:latest python
>>> from mpi4py import MPI
```

**Comment by rscohn2** [comment]
Thanks for reporting it. I will check it on Monday.

Robert

**Comment by rscohn2** [comment]
Hi Tyler,

I am not able to reproduce the problem. Your message above does not show the 'Python 3.6.3 ..' message. Is that something you filtered out? This is docker, so I would only expect the underlying kernel and version of docker to matter. I included that information below. What do you see?

rscohn1@fxsatlin01:~/local/ws$ docker run -it --rm intelpython/intelpython3_full:2018.0.1 python
Python 3.6.3 |Intel Corporation| (default, Oct 16 2017, 15:28:36)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> from mpi4py import MPI
>>>

rscohn1@fxsatlin01:~/local/ws$ uname -a
Linux fxsatlin01 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
rscohn1@fxsatlin01:~/local/ws$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
rscohn1@fxsatlin01:~/local/ws$

**Comment by TylerBackman** [comment]
I am running docker on OSX so I ran uname within the container so you can see the kernel version. See below for the full output:

```
$ docker run -it --rm intelpython/intelpython3_full:2018.0.1 /bin/bash
root@a8a8910fd98f:/# python
Python 3.6.3 |Intel Corporation| (default, Oct 16 2017, 15:28:36)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> from mpi4py import MPI
Segmentation fault
root@a8a8910fd98f:/# uname -a
Linux a8a8910fd98f 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 GNU/Linux
```

Docker version output running on OSX:
```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by rscohn2** [comment]
Someone else on the team has reproduced the problem on a mac and we are investigating.
